-- 코드를 입력하세요
SELECT MONTH(START_DATE) as MONTH, CAR_ID, COUNT(CAR_ID) as RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE_FORMAT(START_DATE, "%Y-%m-%d") >= "2022-08-01" and DATE_FORMAT(START_DATE, "%Y-%m-%d") < "2022-11-01"
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5
    )
    AND DATE_FORMAT(START_DATE, "%Y-%m-%d") >= "2022-08-01" and DATE_FORMAT(START_DATE, "%Y-%m-%d") < "2022-11-01"
GROUP BY MONTH, CAR_ID
HAVING RECORDS > 0
ORDER BY MONTH, CAR_ID desc