-- 코드를 입력하세요

WITH RECURSIVE TEMP AS (
    SELECT 0 as HOUR
    UNION ALL
    SELECT HOUR + 1 FROM TEMP
    WHERE HOUR < 23
)

SELECT tmp.HOUR, COUNT(HOUR(ao.DATETIME)) as COUNT
FROM TEMP tmp
LEFT JOIN ANIMAL_OUTS ao
ON tmp.HOUR = HOUR(ao.DATETIME)
GROUP BY tmp.HOUR
ORDER BY HOUR