-- 코드를 입력하세요
SELECT mp.MEMBER_NAME, rev.REVIEW_TEXT, DATE_FORMAT(rev.REVIEW_DATE, "%Y-%m-%d") as REVIEW_DATE
FROM MEMBER_PROFILE mp
JOIN REST_REVIEW rev
ON mp.MEMBER_ID = rev.MEMBER_ID
WHERE mp.MEMBER_ID = (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(REVIEW_ID) desc
    LIMIT 1
)
ORDER BY rev.REVIEW_DATE, rev.REVIEW_TEXT