-- 코드를 입력하세요
SELECT hist.HISTORY_ID,
    ROUND(
    (CASE WHEN DATEDIFF(hist.END_DATE, hist.START_DATE) + 1 >= 90 THEN 0.85
    WHEN DATEDIFF(hist.END_DATE, hist.START_DATE) + 1 >= 30 THEN 0.92
    WHEN DATEDIFF(hist.END_DATE, hist.START_DATE) + 1 >= 7 THEN 0.95 
    ELSE 1
    END) * 
    car.DAILY_FEE * (DATEDIFF(hist.END_DATE, hist.START_DATE) + 1), 0)
    as FEE
FROM CAR_RENTAL_COMPANY_CAR car
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY hist
ON car.CAR_ID = hist.CAR_ID
WHERE car.CAR_TYPE = "트럭"
ORDER BY FEE desc, hist.HISTORY_ID desc