-- 코드를 입력하세요
SELECT DISTINCT(crcrh.CAR_ID) as CAR_ID
FROM CAR_RENTAL_COMPANY_CAR crcc
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY crcrh
ON crcc.CAR_ID = crcrh.CAR_ID
WHERE crcc.CAR_TYPE = "세단" and crcrh.START_DATE >= '2022-10-01'
ORDER BY crcrh.CAR_ID desc